Financas/Controllers/DespesaController.cs
using Financas.Context;
using Financas.Models;
using Microsoft.AspNetCore.Mvc;

namespace Financas.Controllers {
    public class DespesaController : Controller {
        public readonly MoneyContext _context;

        public DespesaController(MoneyContext context) {
            _context = context;
        }

        public IActionResult Create() {
            return PartialView();
        }

        [HttpPost]
        public IActionResult Create(Despesa despesa) {
            var userId = HttpContext.User.Claims.Single(x => x.Type == "Id");
            int id = Convert.ToInt32(userId.Value);

            if(!ModelState.IsValid)
                return BadRequest(ModelState);

            Conta conta = _context.Contas.Find(id);
            conta.Despesas ??= new List<Despesa>();
            conta.Despesas.Add(despesa);

            _context.Contas.Update(conta);
            _context.SaveChanges();
            return RedirectToAction(actionName: "Index", controllerName: "Home");
        }

        public IActionResult Delete(int id) {
            var dbConta = _context.Despesas.Find(id);

            if(dbConta == null) 
                return NotFound();

            _context.Despesas.Remove(dbConta);
            _context.SaveChanges();
            return Ok();
        }

        public IActionResult Edit(Despesa despesa) {
            if(!ModelState.IsValid)
                return BadRequest(ModelState);

            _context.Despesas.Update(despesa);
            _context.SaveChanges();
            return Ok();
        }
    }
}

Financas/Controllers/HomeController.cs
using Financas.Context;
using Financas.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text;
using Newtonsoft.Json;

namespace Financas.Controllers {
    [Authorize]
    public class HomeController : Controller {
        public readonly MoneyContext _context;
        public readonly PasswordHasher<Conta> _passwordHasher;

        public HomeController(MoneyContext context, PasswordHasher<Conta> passwordHasher) {
            _context = context;
            _passwordHasher = passwordHasher;
        }

        public IActionResult Index() {
            var userId = HttpContext.User.Claims.Single(x => x.Type == "Id");
            int id = Convert.ToInt32(userId.Value);
            var query = from conta in _context.Contas
                        where conta.Id == id
                        select new Conta {
                            Saldo = conta.Saldo,
                            TotalDeDespesas = conta.Despesas.Sum(x => x.Valor),
                            Despesas = conta.Despesas,
                            Transacoes = conta.Transacoes,
                            Login = conta.Login,
                            Metas = conta.Metas,
                            BalançoDeSaldoComDespesa = conta.Saldo - conta.Despesas.Sum(x => x.Valor)
                        };
            Conta usuario = query.FirstOrDefault();
            /*
            var query = from contaCalc in
                            from conta in _context.Contas
                            where conta.Id == id
                            join despesa in _context.Despesas on conta.Id equals id
                            select new Conta { 
                                Saldo = conta.Saldo,
                                Despesas = conta.Despesas,
                                TotalDeDespesas = conta.Despesas.Sum(x => x.Valor)
                            }
                        select new Conta { Saldo = contaCalc., };
            */
            //var conta = _context.Contas.Find(Convert.ToInt32(userId.Value));
            return View(usuario);
        }

        public IActionResult Forbidden() {
            return View();
        }
    }
}

Financas/Views/Home/Forbidden.cshtml
@{
    ViewData["Title"] = "Não autorizado";
}
<h1>Não Autorizado</h1>
<a class="btn btn-secondary" asp-controller="Home" asp-action="Index">Voltar</a>
<a class="btn btn-primary" asp-controller="Home" asp-action="Logout">Logout</a>

Financas/Views/Home/Index.cshtml
@model Financas.Models.Conta
@{
    ViewData["Title"] = "Minha Conta";
    ViewData["Style"] = new string[] { "/css/home.css" };
}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">@Html.DisplayNameFor(x => x.Saldo)</h5>
                <p class="card-text text-center">@Model.Saldo</p>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">@Html.DisplayNameFor(x => x.TotalDeDespesas)</h5>
                <p class="card-text text-center">@Model.TotalDeDespesas</p>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">@Html.DisplayNameFor(x => x.BalançoDeSaldoComDespesa)</h5>
                <p class="card-text text-center">@Model.BalançoDeSaldoComDespesa</p>
            </div>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h5 class="card-title">@Html.DisplayNameFor(x => x.Despesas)</h5>
        <button class="btn btn-success" asp-controller="Despesa" asp-action="Create" onclick="getForm('D')">+</button>
        <table class="table">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(x => x.Despesas.FirstOrDefault().Nome)</th>
                    <th>@Html.DisplayNameFor(x => x.Despesas.FirstOrDefault().Valor)</th>
                    <th>@Html.DisplayNameFor(x => x.Despesas.FirstOrDefault().DataCobranca)</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @if(Model.Despesas == null) {
                    <tr>
                        <td colspan="4" align="center">Não há despesas cadastradas.</td>
                    </tr>
                }
                else {
                    @foreach(var despesa in Model.Despesas) {
                        <tr>
                            <td>@despesa.Nome</td>
                            <td>@despesa.Valor</td>
                            <td>@despesa.DataCobranca</td>
                            <td>
                                <a class="btn btn-danger" asp-controller="Despesa" asp-action="Delete" asp-route-id="@despesa.Id">X</a>
                                <a class="btn btn-primary" asp-controller="Despesa" asp-action="Edit" asp-route-id="@despesa.Id">E</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<div class="container janela" id="formAdd"></div>